import client from './client'

export const listSubjects = () => client.get('/courses/subjects')
export const listTeachers = (subjectId) => client.get(`/courses/subjects/${subjectId}/teachers`)
export const getTeacher = (id) => client.get(`/courses/teachers/${id}`)
export const getAvailableDays = (id, year, month) => client.get(`/courses/teachers/${id}/available-days`, { params: { year, month } })
export const getSlotsByDate = (id, date) => client.get(`/courses/teachers/${id}/slots`, { params: { date } })
export const createBooking = (data) => client.post('/courses/bookings', data)
export const myBookings = () => client.get('/courses/my-bookings')
export const cancelBooking = (id) => client.delete(`/courses/my-bookings/${id}`)

// 教师端
export const teacherApply = (data) => client.post('/teacher/apply', data)
export const teacherProfile = () => client.get('/teacher/profile')
export const updateTeacherProfile = (data) => client.put('/teacher/profile', data)
export const teacherSlots = (params) => client.get('/teacher/slots', { params })
export const createSlot = (data) => client.post('/teacher/slots', data)
export const createSlotsBatch = (slots) => client.post('/teacher/slots/batch', { slots })
export const recognizeSchedule = (formData) => client.post('/teacher/schedule/recognize', formData)
export const pollRecognizeJob = (jobId) => client.get(`/teacher/schedule/recognize/${jobId}`)
export const deleteSlot = (id) => client.delete(`/teacher/slots/${id}`)
export const addStudentToSlot = (slotId, data) => client.post(`/teacher/slots/${slotId}/add-student`, data)
export const addOfflineStudentToSlot = (slotId, data) => client.post(`/teacher/slots/${slotId}/add-offline-student`, data)
export const linkStudentUser = (id, data) => client.post(`/teacher/students/${id}/link-user`, data)
export const teacherBookings = (status) => client.get('/teacher/bookings', { params: { status } })
export const confirmBooking = (id, data) => client.post(`/teacher/bookings/${id}/confirm`, data)
export const teacherCancelBooking = (id, data) => client.post(`/teacher/bookings/${id}/cancel`, data)
export const completeBooking = (id, data) => client.post(`/teacher/bookings/${id}/complete`, data)
export const uncompleteBooking = (id) => client.post(`/teacher/bookings/${id}/uncomplete`)
export const addLessonsBatch = (id, data) => client.post(`/teacher/students/${id}/lessons/batch`, data)

// 课时结算 / 学生管理（全老师端）
export const teacherStats = (year, month) => client.get('/teacher/stats', { params: { year, month } })
export const teacherMonthlyReport = (year, month) => client.get('/teacher/monthly-report', { params: { year, month } })
export const teacherStudents = (includeArchived) => client.get('/teacher/students', { params: { includeArchived } })
export const teacherStudentDetail = (id) => client.get(`/teacher/students/${id}`)
export const addTeacherStudent = (data) => client.post('/teacher/students', data)
export const updateTeacherStudent = (id, data) => client.put(`/teacher/students/${id}`, data)
export const addLesson = (id, data) => client.post(`/teacher/students/${id}/lessons`, data)
export const deleteLesson = (id) => client.delete(`/teacher/lessons/${id}`)
export const updateLesson = (id, data) => client.put(`/teacher/lessons/${id}`, data)
export const getExternalLessons = () => client.get('/teacher/external-lessons')
export const addPayment = (id, data) => client.post(`/teacher/students/${id}/payments`, data)
export const deletePayment = (id) => client.delete(`/teacher/payments/${id}`)

// 管理端
export const adminListSubjects = () => client.get('/admin/subjects')
export const adminCreateSubject = (data) => client.post('/admin/subjects', data)
export const adminUpdateSubject = (id, data) => client.put(`/admin/subjects/${id}`, data)
export const adminDeleteSubject = (id) => client.delete(`/admin/subjects/${id}`)
export const adminTeacherApplications = (status) => client.get('/admin/teacher-applications', { params: { status } })
export const adminApproveTeacher = (id) => client.post(`/admin/teacher-applications/${id}/approve`)
export const adminRejectTeacher = (id, data) => client.post(`/admin/teacher-applications/${id}/reject`, data)
export const adminRevokeTeacher = (id, data) => client.post(`/admin/teacher-applications/${id}/revoke`, data)

// 管理端 — 教师管理（行情分析 / 月报）
export const adminListTeachers = () => client.get('/admin/teachers')
export const adminGetTeacher = (id, year, month) => client.get(`/admin/teachers/${id}`, { params: { year, month } })
export const adminGetTeacherStudents = (id, includeArchived) => client.get(`/admin/teachers/${id}/students`, { params: { includeArchived } })
export const adminGetTeacherStudentDetail = (id, sid) => client.get(`/admin/teachers/${id}/students/${sid}`)
export const adminUpdateTeacherSubjects = (id, subjectIds) => client.put(`/admin/teachers/${id}/subjects`, { subjectIds })
